# This notebook has been separately created to deal with abagen specific cells. 
## abagen uses older versions of numpy and so needs it's own kernel

In [17]:
import abagen
import pandas as pd

In [18]:
atlas = abagen.fetch_desikan_killiany()
atlas_image = atlas['image']
atlas_info = pd.read_csv(atlas['info'])
atlas_info.to_csv("../datasets/processed/dk_atlas_info.csv", index=False)
print(atlas_info.columns)
atlas_info.head()

Index(['id', 'label', 'hemisphere', 'structure'], dtype='object')

   id                    label hemisphere structure
0   1                 bankssts          L    cortex
1   2  caudalanteriorcingulate          L    cortex
2   3      caudalmiddlefrontal          L    cortex
3   4                   cuneus          L    cortex
4   5               entorhinal          L    cortex

In [19]:
donor_ids = ['9861', '10021', '12876', '14380', '15496', '15697']

for donor in donor_ids:
    try:
        abagen.fetch_microarray(donors=[donor], resume=True)
        print(f"Donor {donor} done")
    except Exception as e:
        print(f"Donor {donor} failed: {e}")

Donor 9861 done
Donor 10021 done
Donor 12876 done
Donor 14380 done
Donor 15496 done
Donor 15697 done

In [20]:
expression = abagen.get_expression_data(atlas_image, atlas_info)
print(expression.shape)
expression.head()

/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/probes_.py:757: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  micro = micro.set_axis(symbols, axis=1, inplace=False)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)
/Users/sannidhyabiswas/Documents/Projekts/Neurogenomic_Disease_ML_Pipeline/abagen-env/lib/python3.10/site-packages/abagen/samples_.py:406: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  .append(labels)

(83, 15633)

gene_symbol,A1BG,A1BG-AS1,A2M,A2ML1,A3GALT2,A4GALT,AAAS,AACS,AADACL3,AADAT,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
label,,,,,,,,,,,,,,,,,,,,,
1,0.498266,0.664570,0.395276,0.449984,0.363204,0.390478,0.525830,0.752044,0.339071,0.687745,...,0.536216,0.510445,0.535749,0.470178,0.552097,0.394286,0.664582,0.675843,0.555539,0.487572
2,0.649068,0.578997,0.496142,0.651378,0.374900,0.376148,0.417392,0.670258,0.468810,0.680613,...,0.436584,0.460258,0.394620,0.439953,0.380107,0.495299,0.632483,0.483165,0.382653,0.504041
3,0.530613,0.623289,0.516300,0.387376,0.438570,0.548449,0.511302,0.785473,0.352448,0.571331,...,0.498757,0.624526,0.478582,0.350420,0.377683,0.361561,0.678239,0.732930,0.359707,0.450664
4,0.357235,0.577027,0.472538,0.407110,0.351562,0.439605,0.652987,0.752140,0.443812,0.564911,...,0.574279,0.579238,0.440776,0.394898,0.427183,0.380926,0.651013,0.845008,0.564132,0.371442
5,0.668703,0.533731,0.595773,0.524926,0.412263,0.446762,0.340154,0.699326,0.478007,0.617597,...,0.452369,0.543893,0.715963,0.371176,0.383864,0.502091,0.715354,0.328519,0.388377,0.557719

In [21]:
expression.to_csv("../datasets/processed/parkinsons_expression_dk.csv")